config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :check_outs do
    member do
      post :complete
    end
  end
  resources :things
end

app/models/check_out.rb
class CheckOut < ActiveRecord::Base
  belongs_to :thing

  validates :quantity, numericality: { greater_than: 0 }
  validate :thing_has_available_quantity, on: :create

  after_create :notify_create

  def pending?
    completed_at.nil?
  end

  def self.pending
    where(completed_at: nil)
  end

  def complete
    update_attributes(completed_at: send(:current_time_from_proper_timezone))
    notify_complete
  end

  private

    def notify_create
      CheckOutNotificationJob.perform_later(self)
    end

    def notify_complete
      CheckOutNotificationJob.perform_later(self)
    end

    def thing_has_available_quantity
      errors.add :quantity, 'not available' if thing.available_quantity < quantity
    end
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  has_many :check_outs, dependent: :destroy

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :name, presence: true, uniqueness: true

  def available?
    available_quantity > 0
  end

  def available_quantity
    quantity - check_out_quantity
  end

  def check_out_quantity
    check_outs.pending.pluck(:quantity).sum
  end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/check_outs_controller.rb
class CheckOutsController < ResourceController
  def create
    @check_out = CheckOut.create(check_out_params)
    respond_with @check_out, location: root_path
  end

  def complete
    @check_out = CheckOut.find(params[:id])
    @check_out.complete
    respond_with @check_out, location: root_path
  end

  private

    def check_out_params
      params.require(:check_out).permit(:thing_id, :name, :quantity)
    end
end

app/controllers/resource_controller.rb
class ResourceController < ApplicationController
  respond_to :html, :json
end

app/controllers/things_controller.rb
class ThingsController < ResourceController
  before_action :load_thing, only: [:show, :edit, :update, :destroy]

  def index
    @things = Thing.all.order(:name)
    respond_with @thing
  end

  def new
    @thing = Thing.new
    respond_with @thing
  end

  def create
    @thing = Thing.create(thing_params)
    respond_with @thing
  end

  def show
    @check_outs = @thing.check_outs
    @check_outs = @check_outs.order('completed_at is null desc, completed_at desc, created_at desc')
  end

  def edit
  end

  def update
    @thing.update_attributes(thing_params)
    respond_with @thing
  end

  def destroy
    @thing.destroy
    respond_with @thing
  end

  private

    def load_thing
      @thing = Thing.find(params[:id])
    end

    def thing_params
      params.require(:thing).permit(:name, :quantity)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @things = Thing.all.includes(:check_outs).order(:name)
    respond_with @things
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags
    = csrf_meta_tags
    %title
      - if content_for?(:title)
        = yield(:title)
        \-
      Check Me Out
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

    - if content_for?(:stylesheets)
      = yield(:stylesheets)

    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  %body
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Check Me Out!', root_path, class: 'navbar-brand'

        #navbar-collapse.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Things', things_path

    - if content_for?(:body_title)
      = yield(:body_title)
    - elsif content_for?(:title)
      .container
        %h1= yield(:title)

    .container
      - flash.each do |type, message|
        - alert_class = case type when 'alert' then 'alert-danger'; when 'notice' then 'alert-info'; end
        .alert{ class: alert_class, role: 'alert' }
          %button.close{ type: 'button', data: { dismiss: 'alert' } } &times;
          = message

    = yield

    %footer
      %hr
      .container
        .text-muted
          %ul.list-inline
            %li= link_to 'Bugs / Suggestions', 'https://github.com/codeintheschools/check_me_out/issues'


    = render partial: 'shared/fork'

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    - if content_for?(:javascripts)
      = yield(:javascripts)

app/views/shared/_fork.html.haml
.hidden-xs.hidden-sm
  %a{:href => "https://github.com/codeintheschools/check_me_out"}
    %img{:alt => "Fork me on GitHub", "data-canonical-src" => "https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png", :src => "https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67", :style => "position: absolute; top: 0; right: 0; border: 0;"}/

app/views/things/_form.html.haml
- thing ||= @thing

= bootstrap_form_for thing do |f|
  = f.alert_message 'Please fix the issues below.'
  = f.text_field :name, placeholder: 'Name', required: true
  = f.number_field :quantity, placeholder: 'Quantity', required: true
  = f.submit

app/views/things/edit.html.erb
<h1>Things#edit</h1>
<p>Find me in app/views/things/edit.html.erb</p>

app/views/things/edit.html.haml
- title @thing.name

.container
  = render partial: 'form'

  .pull-right
    = button_to @thing, method: :delete, class: 'btn btn-danger' do
      %span.glyphicon.glyphicon-trash
      Delete Thing

app/views/things/index.html.haml
- title 'Things'

.container
  = link_to new_thing_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-asterisk
    New Thing

  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th.text-right Quantity

    %tbody
      - @things.each do |thing|
        %tr
          %td= link_to thing.name, thing_path(thing)
          %td.text-right= thing.quantity

app/views/things/new.html.haml
- title 'New Thing'

.container
  = render partial: 'form'

app/views/things/show.html.haml
- title @thing.name

.container
  = link_to 'Edit Thing', edit_thing_path(@thing), class: 'btn btn-default'

  Quantity:
  %strong= @thing.quantity
  Available:
  %strong= @thing.available_quantity
  Checked Out:
  %strong= @thing.check_out_quantity

  %table.table
    %thead
      %tr
        %th Checked Out
        %th Returned
        %th Quantity
        %th Name
    %tbody
      - @check_outs.each do |check_out|
        %tr{ class: check_out.pending? ? 'warning' : 'success' }
          %td
            = time_ago_in_words check_out.created_at
            ago
          %td
            - if check_out.completed_at
              = time_ago_in_words check_out.completed_at
              ago
            - else
              Pending
          %td= check_out.quantity
          %td= check_out.name

app/views/welcome/index.html.haml
- title 'Home'

.container-fluid
  .row
    - @things.each_with_index do |thing, i|
      .col-lg-3.col-md-4.col-sm-6
        .panel.panel-default
          .panel-heading
            .pull-right
              - if thing.available?
                .label.label-success Available
              - else
                .label.label-danger Checked Out

            = link_to thing.name, thing_path(thing)

          - if thing.quantity > 1
            .panel-body
              Available
              %strong= thing.available_quantity
              (
              Total
              = thing.quantity
              )

          - pending_check_outs = thing.check_outs.pending
          - if pending_check_outs.any?
            %table.table.table-condensed.table-striped
              %thead
                %tr.warning
                  %th{ colspan: 4 }
                    = thing.check_out_quantity
                    Checked Out
              %tbody
                - pending_check_outs.each do |check_out|
                  %tr
                    %td= check_out.quantity
                    %td= check_out.name
                    %td
                      = time_ago_in_words check_out.created_at
                      ago
                    %td.text-right
                      = button_to complete_check_out_path(check_out), method: :post, class: 'btn btn-xs btn-default', title: 'Return Things' do
                        %span.glyphicon.glyphicon-check

          - if thing.available_quantity > 0
            .panel-body
              = form_for CheckOut.new(thing: thing, quantity: 1) do |f|
                = f.hidden_field :thing_id
                = f.text_field :name, placeholder: 'Name', class: 'form-control'
                - if thing.quantity > 1
                  = f.number_field :quantity, placeholder: 'Quantity', class: 'form-control', max: thing.available_quantity, min: 1, step: 1
                - else
                  = f.hidden_field :quantity

                %button.btn.btn-default{ type: 'submit' }
                  %span.glyphicon.glyphicon-share
                  Check Out
      - if i % 4 == 3
        .clearfix.visible-lg-block
      - if i % 3 == 2
        .clearfix.visible-md-block
      - if i % 2 == 1
        .clearfix.visible-sm-block

- content_for :body_title do
  / Nothing here!